### ISSUE TITLE
Fukuday

### ISSUE THREAD

**Issue by languard** [Deevad/peppercarrot#2]
Is the name of this day set in stone?  Because in English, that is really easy to read as 'F**k You Day' which is obviously not good.  Perhaps change it to Fookuday for the 'Foo' sound instead of 'Fu'.

**Comment by Deevad** [comment]
Hey, Nothing is set in stone and thanks you @languard for the feedback.
I'll change it to Fookuday  :-)

**Comment by Deevad** [comment]
Done: http://www.peppercarrot.com/en/static8/wiki&page=Time-system  
thanks again.
