### ISSUE TITLE
AmA on reddit

### ISSUE THREAD

**Issue by aloisdg** [Deevad/peppercarrot#8]
Hello,

Today, I shared Pepper & Carrot on the french subreddit /r/france. Could you do an Ask me Anything about your life as an artist in the FOSS world. If you don't know what is an AmA, it as a kind of press conference but textual and online. For example, the author Jean-Philippe Jaworski did one today: [Rencontre avec Jean-Philippe Jaworski](https://www.reddit.com/r/france/comments/6n148e/ama_rencontre_avec_jeanphilippe_jaworski).

I am willing to help you, if you don't feel at ease with Reddit.

Thank you!

-----

Bonjour,

Aujourd'hui j'ai partagé Pepper & Carrot sur le subreddit français /r/france. Peux-tu faire un AmA sur la vie d'artiste dans le monde du libre. Si tu ne sais pas ce qu'est un AmA, c'est une sorte de conférence de presse textuelle et en ligne. Par exemple, l'auteur Jean-Philippe Jaworski en a réalisé un aujourd'hui : [Rencontre avec Jean-Philippe Jaworski](https://www.reddit.com/r/france/comments/6n148e/ama_rencontre_avec_jeanphilippe_jaworski).

Je suis disposé à t'aider, si tu ne te sens pas a l'aise avec Reddit.

Merci !

Alois

**Comment by Deevad** [comment]
Hi @aloisdg !

_(I'll keep the answer in English, because this thread is read by international contributors with Github notifications. Thank you for translating your message in both lang)_

I'm very honored to receive your invitation to a AmA about my french life as an artist in the FOSS world. I'm not sure if it will be really interesting by the way but let's try;  I'm available any afternoon starting the next week (Mon 17 July)  till the end July, you decide.

**Comment by aloisdg** [comment]
I know he can be quite frustrating and not welcoming to be in front of foreign language. As a french/english speaker contributing to chinese content is quite hard 😕 

For the Ama, thank you for your answer! I think it may encourage people to read/write libre content. I shared your availability to /r/france's mods. Are you familiar with Reddit?

**Comment by Deevad** [comment]
> Are you familiar with Reddit?

I have a basic skill to write comments and format my replies. I also understand the concept of upvote/downvote.  You can find my profile here: https://www.reddit.com/user/davidrevoy/

**Comment by aloisdg** [comment]
@Deevad It is far from enough. Reddit is not very popular in France so I prefer ask :)

**Comment by aloisdg** [comment]
Bonus I connected the Pepper&Carrot's feed to a Naut-based [subreddit](https://www.reddit.com/r/PepperAndCarrot). Your mod invitation should arrive soon.

**Comment by Deevad** [comment]
Oh, thank you for https://www.reddit.com/r/PepperAndCarrot/  , I really like the theme of the sub, good job!

A contributor on Reddit, Nuparu made this sub https://www.reddit.com/r/PepperCarrot/ two years ago, and as a coincidence Singpolyma started to maintain this old sub 24h before your message here via making a bot who auto-post RSS of www.peppercarrot.com ;  do you know if it's possible to merge sub? Maybe Nuparu could destroy old PepperCarrot ( I prefer your theme , and name PepperAndCarrot ) and I can ask Singpolyma to redirect his RSS bot to r/PepperAndCarrot/  ?

**Comment by aloisdg** [comment]
I didnt find /r/PepperCarrot/ . The sub I created is already fed with the Pepper&Carrot's RSS. The theme is not very hard to copy/paste on the other sub. I just need to be a mod or to be in contact with one.

**Comment by aloisdg** [comment]
I got an answer from /r/france mods. They advise on Wednesday evening. Is it fine for you?

**Comment by Deevad** [comment]
Ha, right. Can you try to contact Nuparu , the creator of the channel https://www.reddit.com/r/PepperCarrot/ ? So we can clean the situation?

The AmA on Wednesday evening is a perfect date ; thank you !

**Comment by aloisdg** [comment]
I will contact him for the sub.

For this evening, if you need any help/recommendation feel free to [PM on Reddit](https://www.reddit.com/message/compose/?to=Dall0o). You can find all /r/france AmA [here](https://www.reddit.com/r/france/search?q=flair%3A%27AMA%27&sort=top&restrict_sr=on). The subreddit speaks mostly in french but english is allowed too.

**Comment by Deevad** [comment]
Thanks for the PM, and for contacting Nuparu about the multi-Pepper&Carrot sub !

For the AMA: ha perfect for the "english" allowed, I have follower maybe interested in this : can I brag a bit about it on the social networks? What type of URL/message/hour do you advice me to send on my social network (twitter/facebook/etc..) to link to the event ? I even don't know myself the hour ; but I'll be around all evening.

**Comment by aloisdg** [comment]
Of course you can talk about it everywhere you. 😄  After creating your Ama, you will be able to share the post's url. For advice about the kind of message to use, you can get some inspiration from the [top](https://www.reddit.com/r/IAmA/top/).  For example [Barack Obama](https://www.reddit.com/r/IAmA/comments/z1c9z/i_am_barack_obama_president_of_the_united_states/) or [Snowden](https://www.reddit.com/r/IAmA/comments/2wwdep/we_are_edward_snowden_laura_poitras_and_glenn/).

You can create the post right now and add a sentence at the end saying that you will start answering later something like: "Je commancerai à répondre à vos questions aux alentours de 19h30." People will start asking for later and you have your link ready to be shared.

**Comment by Deevad** [comment]
Thank you for the advices. I posted this: https://twitter.com/davidrevoy/status/887698544756445184 , and I'll do an update later with the final thread URL.
I'll be ready at 19h30 :)

**Comment by Deevad** [comment]
It's online here now , I hope everything is ok @aloisdg  ; feel free to edit if you moderate ( I believe you do ) :

https://www.reddit.com/r/france/comments/6oa1h1/je_suis_david_revoy_auteur_du_webcomic_libre_et/

I failed to add the [AMA] tag ; and I just saw all the link I spread on social network filter using [AMA] as a keyword , but I couldn't see it because the %27 of the URL encoding  :/  Is it possible to fix ?

**Comment by aloisdg** [comment]
@Deevad I am not a moderator of /r/france , but I am in contact with them. The flag is here now. Good luck!

**Comment by Deevad** [comment]
Ok , done ! 

Thank you **very much** @aloisdg for your initiative organising this event, it was a pleasure to participate to my first AMA ; and thank you also for your quality set of questions. I'm closing this "issue" now, have a good end of week!

**Comment by aloisdg** [comment]
Thank you for your answers. The thread was great to read. You stayed late! It was really nice. Have a nice day and a goof end of week too! :)
